module.exports={
apps:[
  {
    name:"EmailAgent-API",
    script:"./dist/entry.js",
    env:{
      NODE_ENV:"production",
      PROCESS_TYPE:"API"
    }
  },
  {
    name:"EmailAgent-Queue",
    script:"./dist/entry.js",
    env:{
      NODE_ENV:"production",
      PROCESS_TYPE:"WORKER"
    }
  },
  {
    name:"EmailAgent-Scheduler",
    script:"./dist/entry.js",
    env:{
      NODE_ENV:"production",
      PROCESS_TYPE:"SCHEDULER"
    }
  }
]

}
